# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: michaelyili
google_analytics: michaelyili

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: michael yi li

description: Stylish Jekyll Theme
author:
  name: YiLi
  email: elyi.lee@gmail.com
  github: michaelyili
  twitter: 2253784074/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
  pinterest: asd123
  linkedin: yi-li-7b889158
  bio: work hard, play harder!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
